name: Python Lint Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '24 8 * * 4'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [flake8, pylint, ruff, mypy, pytype, pyright, fixit]
    steps:
      - name: Run Python Lint
        uses: advanced-security/python-lint-code-scanning-action@main
        with:
          linter: ${{ matrix.linter }}
